export { DatosPersonales } from './DatosPersonales'
export { Identificacion } from './Identificacion'
export { DatosMonetarios } from './DatosMonetarios'
export { Beneficiario } from './Beneficiario'
export { CodeVerify } from './CodeVerify'
export { SuccessAccount } from './SuccessAccount'